#!/usr/bin/env node
/**
 * P0B 基线 inventory（v4 §10 P0B / §2 / §5.3）
 * 从固定基线（当前 checkout）生成可审计 manifest：
 *   manifests/p0b/inventory.json          74 源正文（frontmatter/hash/heading ID/媒体引用/iframe）
 *   manifests/p0b/media.json              全部媒体（sha256/引用者/orphan/目标资产路径）
 *   manifests/p0b/categories.json         10 组分类语义（zh/en 标题与描述 + 新路径 + 顺序）
 *   manifests/p0b/page-locale-matrix.json page × locale 发布矩阵（旧路径→新路径映射）
 *   manifests/p0b/site-routes.json        新站全量路由（publishTo* 标志）
 *   manifests/p0b/greenfield-deny.json    旧页面/旧媒体/anchor alias 负向验收集
 *
 * 运行前置：基线 checkout 上 `npm run build`（旧站构建产物提供权威旧 URL/资产）。
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { pathToFileURL } from 'node:url';

const ROOT = path.resolve(import.meta.dirname, '../..');
const OUT_DIR = path.join(ROOT, 'manifests/p0b');

// ---------------------------------------------------------------------------
// 新 IA 决策表（v4 §5.2：目标路径完全由新信息架构决定，不继承旧 slug）
// ---------------------------------------------------------------------------
const CATEGORY_MAP = {
  // 旧 slug（generated-index） → 新分类路径（content/docs 下目录名）
  '/overview': 'overview',
  '/quick-start': 'quick-start',
  '/user-guide': 'user-guide',
  '/data-collection': 'data-collection',
  '/data-collection/case-introduction': 'data-collection/case-introduction',
  '/integration': 'integration',
  '/docs/openapi': 'openapi', // 旧 slug 带 /docs 前缀，新 IA 修正为 /openapi
  '/deploy-and-dev': 'deploy-and-dev',
  '/faq': 'faq',
  '/changelog': 'changelog',
};

const PAGE_MAP = {
  // 旧 sidebar item id → 新页面路径（相对 content/docs，无 locale 后缀）
  intro: 'overview/intro',
  'resources-and-support': 'overview/resources-and-support',
  'quick-start/first-login': 'quick-start/first-login',
  'quick-start/demonstrations': 'quick-start/demonstrations',
  'data-collection/data-collection-instructions': 'data-collection/data-collection-instructions',
  'data-collection/case-introduction/data-evaluation':
    'data-collection/case-introduction/data-evaluation',
  'data-collection/case-introduction/model-building':
    'data-collection/case-introduction/model-building',
  'data-collection/case-introduction/unit-process-construction':
    'data-collection/case-introduction/unit-process-construction',
  'MCP/lca_local': 'integration/mcp-lca-local',
  'MCP/lca_remote': 'integration/mcp-lca-remote',
  'MCP/KB_remote': 'integration/mcp-kb-remote',
  'integration/cli': 'integration/cli',
  'openapi/tidas-package-import': 'openapi/tidas-package-import',
  'deploy/local-deploy': 'deploy-and-dev/local-deploy',
  'dev/dev-env': 'deploy-and-dev/dev-env',
  'dev/docs-product-sync': 'deploy-and-dev/docs-product-sync',
  'changelog/function-update': 'changelog/function-update',
  // user-guide/* 与 faq/* 保持目录内同名迁移（脚本自动补全）
};

function pageMapFor(id) {
  if (PAGE_MAP[id]) return PAGE_MAP[id];
  if (id.startsWith('user-guide/')) return `user-guide/${id.slice('user-guide/'.length)}`;
  if (id.startsWith('faq/')) return `faq/${id.slice('faq/'.length)}`;
  throw new Error(`no new-IA mapping for sidebar item: ${id}`);
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------
const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');
const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));
const slugify = (name) =>
  name
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9._-]/g, '')
    .replace(/-+/g, '-');

function parseFrontmatter(text) {
  const fm = {};
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return fm;
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([a-zA-Z_][\w-]*):\s*(.*)$/);
    if (kv) fm[kv[1]] = kv[2].replace(/^["']|["']$/g, '');
  }
  return fm;
}

function walkSidebar(items, categoryTrail, categories, orderedIds) {
  for (const item of items) {
    if (typeof item === 'string') {
      orderedIds.push(item);
    } else if (item.type === 'category') {
      const slug = item.link?.slug ?? `/category/${item.label}`;
      const newBase = CATEGORY_MAP[slug];
      if (!newBase) throw new Error(`unmapped category slug: ${slug}`);
      categories.push({
        oldSlug: slug,
        newBase,
        labelZh: item.label,
        titleZh: item.link?.title ?? item.label,
        descriptionZh: item.link?.description ?? '',
        depth: categoryTrail.length,
        parent: categoryTrail[categoryTrail.length - 1] ?? null,
      });
      walkSidebar(item.items, [...categoryTrail, slug], categories, orderedIds);
    } else if (item.type === 'doc') {
      orderedIds.push(item.id);
    }
    // type 'link'（外链）与 'autogenerated' 不产生本仓页面
  }
}

// ---------------------------------------------------------------------------
// 1. 侧边栏 → 分类语义 + 有序页面 id
// ---------------------------------------------------------------------------
// sidebars.ts 在 P1 后已从工作树删除：从基线 commit 提取（manifest 可复现性要求固定基线）
import { execSync } from 'node:child_process';
const BASELINE = 'e44e9b4d12197665265a88713f9ca7a5d52264f5';
const sidebarsTmp = path.join(ROOT, '.p0b-sidebars.tmp.ts');
fs.writeFileSync(sidebarsTmp, execSync(`git show ${BASELINE}:sidebars.ts`).toString());
const sidebars = (await import(pathToFileURL(sidebarsTmp).href)).default;
fs.rmSync(sidebarsTmp);
const categories = [];
const orderedIds = [];
walkSidebar(sidebars.tutorialSidebar, [], categories, orderedIds);

const enTranslations = readJson(
  path.join(ROOT, 'i18n/en/docusaurus-plugin-content-docs/current.json'),
);
for (const c of categories) {
  const key = `sidebar.tutorialSidebar.category.${c.labelZh}`;
  c.labelEn = enTranslations[`${key}`]?.message ?? c.labelZh;
  c.titleEn = enTranslations[`${key}.link.generated-index.title`]?.message ?? c.labelEn;
  c.descriptionEn =
    enTranslations[`${key}.link.generated-index.description`]?.message ?? '';
}

// ---------------------------------------------------------------------------
// 2. 源页面扫描（zh: docs/**，en: i18n/en/.../current/**）
// ---------------------------------------------------------------------------
const EN_BASE = 'i18n/en/docusaurus-plugin-content-docs/current';
function scanPage(docId) {
  const relZh = `docs/${docId}.md`;
  const relEn = `${EN_BASE}/${docId}.md`;
  const result = { id: docId, newPath: pageMapFor(docId) };
  for (const [locale, rel] of [['zh', relZh], ['en', relEn]]) {
    const abs = path.join(ROOT, rel);
    if (!fs.existsSync(abs)) {
      result[locale] = null;
      continue;
    }
    const text = fs.readFileSync(abs, 'utf8');
    const headingIds = [...text.matchAll(/^#{1,6}\s+.*\{#([^}]+)\}\s*$/gm)].map((m) => m[1]);
    const mediaRefs = [
      ...text.matchAll(/!\[[^\]]*\]\(([^)]+)\)/g),
      ...text.matchAll(/<img[^>]+src=["']([^"']+)["']/g),
    ].map((m) => m[1]);
    result[locale] = {
      sourcePath: rel,
      sha256: sha256(Buffer.from(text)),
      frontmatter: parseFrontmatter(text),
      explicitHeadingIds: headingIds,
      mediaRefs,
      hasIframe: /<iframe[\s>]/.test(text),
      hasJsx: /<\/?[A-Z][A-Za-z]*[\s>]/.test(text),
    };
  }
  return result;
}

const pages = orderedIds.map(scanPage);
const missingEn = pages.filter((p) => !p.en).map((p) => p.id);
const missingZh = pages.filter((p) => !p.zh).map((p) => p.id);
if (missingZh.length > 0) throw new Error(`zh source missing: ${missingZh}`);

// docs/ 树中不在 sidebar 的公开页（防漏）
const allZhMd = new Set(
  (await fs.promises.readdir ? walkMd('docs') : []).map((p) => p.replace(/^docs\//, '').replace(/\.md$/, '')),
);
function walkMd(dir) {
  const out = [];
  for (const e of fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true })) {
    const rel = `${dir}/${e.name}`;
    if (e.isDirectory()) out.push(...walkMd(rel));
    else if (/\.(md|mdx)$/.test(e.name) && !rel.startsWith('docs/agents/')) out.push(rel);
  }
  return out;
}
const sidebarIds = new Set(orderedIds);
const orphanZhPages = [...allZhMd].filter((id) => !sidebarIds.has(id));

// ---------------------------------------------------------------------------
// 3. 媒体清单（docs/** 与 en 镜像的 img 目录；按 sha256 去重）
// ---------------------------------------------------------------------------
function walkFiles(dir, exts) {
  const out = [];
  const abs = path.join(ROOT, dir);
  if (!fs.existsSync(abs)) return out;
  for (const e of fs.readdirSync(abs, { withFileTypes: true })) {
    const rel = `${dir}/${e.name}`;
    if (e.isDirectory()) out.push(...walkFiles(rel, exts));
    else if (exts.some((x) => e.name.toLowerCase().endsWith(x))) out.push(rel);
  }
  return out;
}

const mediaSources = [
  ...walkFiles('docs', ['.png', '.jpg', '.jpeg', '.svg', '.webp', '.gif', '.mp4']),
  ...walkFiles(EN_BASE, ['.png', '.jpg', '.jpeg', '.svg', '.webp', '.gif', '.mp4']),
];
const mediaByHash = new Map();
for (const rel of mediaSources) {
  const buf = fs.readFileSync(path.join(ROOT, rel));
  const hash = sha256(buf);
  const name = path.basename(rel);
  if (!mediaByHash.has(hash)) {
    mediaByHash.set(hash, {
      sha256: hash,
      size: buf.length,
      targetAssetPath: `/assets/docs/${hash.slice(0, 8)}/${slugify(name)}`,
      sourcePaths: [],
      referencedBy: [],
    });
  }
  const entry = mediaByHash.get(hash);
  entry.sourcePaths.push(rel);
}

// 引用解析：markdown 相对引用 → 相对页面目录解析
for (const page of pages) {
  for (const locale of ['zh', 'en']) {
    const p = page[locale];
    if (!p) continue;
    const pageDir = path.dirname(p.sourcePath);
    for (const ref of p.mediaRefs) {
      if (/^(https?:)?\/\//.test(ref)) continue; // 外链
      const clean = decodeURIComponent(ref.split(' ')[0]);
      const resolved = path.posix.normalize(path.posix.join(pageDir, clean));
      const found = [...mediaByHash.values()].find((m) =>
        m.sourcePaths.some((sp) => sp === resolved),
      );
      if (found) found.referencedBy.push(`${locale}:${page.id}`);
    }
  }
}
const media = [...mediaByHash.values()];
const orphanMedia = media.filter((m) => m.referencedBy.length === 0);

// ---------------------------------------------------------------------------
// 4. 旧 URL（build/sitemap.xml 为权威源；en = /en + zh 路径推导）
// ---------------------------------------------------------------------------
const sitemapXml = fs.readFileSync(path.join(ROOT, 'build/sitemap.xml'), 'utf8');
const oldZhUrls = [...sitemapXml.matchAll(/<loc>https:\/\/docs\.tiangong\.earth([^<]*)<\/loc>/g)]
  .map((m) => m[1]);
const REDEFINED = new Set(['/', '/llms.txt', '/robots.txt', '/sitemap.xml']);
const oldPages = [
  ...oldZhUrls.filter((u) => !REDEFINED.has(u)),
  ...oldZhUrls.filter((u) => !REDEFINED.has(u)).map((u) => `/en${u === '/' ? '/' : u}`),
];

const oldMediaUrls = [
  ...walkFiles('build/assets/images', ['.png', '.jpg', '.svg', '.webp', '.gif', '.mp4']).map(
    (p) => `/${p.replace(/^build\//, '')}`,
  ),
  ...walkFiles('static/img', ['.png', '.svg', '.jpg', '.ico']).map((p) => `/${p.replace(/^static\//, '')}`),
];

const anchorAliases = pages.flatMap((p) =>
  (p.zh?.explicitHeadingIds ?? []).map((id) => ({ oldPage: `/${p.id}`, anchor: id })),
);

// ---------------------------------------------------------------------------
// 5. 新站路由 manifest
// ---------------------------------------------------------------------------
const routes = [
  { route: '/', locale: null, pageType: 'language-entry', sitemap: true, llms: false, search: false, context7: false },
];
for (const lang of ['zh', 'en', 'de', 'fr']) {
  routes.push({ route: `/${lang}/`, locale: lang, pageType: 'locale-home', sitemap: true, llms: false, search: false, context7: false });
}
// docs 首页：zh/en 为完整落地页；de/fr 为已审核翻译的真实内容（进入 llms/search）
for (const lang of ['zh', 'en', 'de', 'fr']) {
  routes.push({
    route: `/${lang}/docs/`, locale: lang, pageType: 'docs-index',
    sitemap: true, llms: true, search: true, context7: lang !== 'de' && lang !== 'fr' ? true : true,
  });
}
// 分类页（仅 zh/en；v4 §2：llms:false search:false）
for (const lang of ['zh', 'en']) {
  for (const c of categories) {
    routes.push({
      route: `/${lang}/docs/${c.newBase}/`, locale: lang, pageType: 'category-index',
      sitemap: true, llms: false, search: false, context7: false,
    });
  }
}
// 正文页（zh/en 全量）
for (const lang of ['zh', 'en']) {
  for (const page of pages) {
    routes.push({
      route: `/${lang}/docs/${page.newPath}/`, locale: lang, pageType: 'doc',
      sitemap: true, llms: true, search: true, context7: true,
    });
  }
}
const systemRoutes = [
  { route: '/llms.txt', pageType: 'system-llms' },
  { route: '/robots.txt', pageType: 'system-robots' },
  { route: '/sitemap.xml', pageType: 'system-sitemap' },
  { route: '/search-records.json', pageType: 'system-search-records' },
  { route: '/api/search', pageType: 'system-search-index' },
  { route: '/og/[...slug]', pageType: 'system-og' },
  { route: '/404', pageType: 'system-404' },
];

// ---------------------------------------------------------------------------
// 6. page × locale 发布矩阵
// ---------------------------------------------------------------------------
const matrix = pages.map((p) => ({
  id: p.id,
  oldZhUrl: `/${p.id}`,
  oldEnUrl: `/en/${p.id}`,
  newPath: p.newPath,
  locales: { zh: Boolean(p.zh), en: Boolean(p.en), de: false, fr: false },
}));

// ---------------------------------------------------------------------------
// 输出 + 交叉校验
// ---------------------------------------------------------------------------
const llmsTxt = fs.readFileSync(path.join(ROOT, 'static/llms.txt'), 'utf8');
const llmsCount = (llmsTxt.match(/^- \[/gm) ?? []).length;

const summary = {
  generatedFrom: {
    commit: process.env.SOURCE_COMMIT ?? null,
    baselineRequirement: 'e44e9b4d12197665265a88713f9ca7a5d52264f5',
  },
  counts: {
    publicZhDocs: pages.filter((p) => p.zh).length,
    publicEnDocs: pages.filter((p) => p.en).length,
    missingEnMirror: missingEn,
    orphanZhPagesNotInSidebar: orphanZhPages,
    categories: categories.length,
    mediaSourceFiles: mediaSources.length,
    mediaUniqueByHash: media.length,
    orphanMedia: orphanMedia.map((m) => ({ target: m.targetAssetPath, sources: m.sourcePaths })),
    oldPageUrlsInDeny: oldPages.length,
    oldMediaUrlsInDeny: oldMediaUrls.length,
    anchorAliases: anchorAliases.length,
    newHtmlRoutes: routes.length,
    llmsTxtEntries: llmsCount,
    llmsTargetEntries: 74 + 2, // 74 基线 + de/fr 首页真实翻译
  },
};

fs.mkdirSync(OUT_DIR, { recursive: true });
const emit = (name, data) =>
  fs.writeFileSync(path.join(OUT_DIR, name), `${JSON.stringify(data, null, 2)}\n`);
emit('inventory.json', { summary, pages });
emit('media.json', { summary: summary.counts, media });
emit('categories.json', categories);
emit('page-locale-matrix.json', matrix);
emit('site-routes.json', { htmlRoutes: routes, systemRoutes });
emit(
  'greenfield-deny.json',
  {
    note: 'v4 §5.3：旧页面/旧媒体无条件 deny（已排除新站重定义端点 /、locale landing、llms.txt、robots.txt、sitemap.xml）；不含旧→新映射',
    oldPages,
    oldMediaUrls,
    anchorAliases,
  },
);

// 校验断言
const problems = [];
if (summary.counts.publicZhDocs !== 37) problems.push(`zh docs = ${summary.counts.publicZhDocs}, expected 37`);
if (summary.counts.publicEnDocs !== 37) problems.push(`en docs = ${summary.counts.publicEnDocs}, expected 37`);
if (missingEn.length > 0) problems.push(`missing en mirror: ${missingEn.join(', ')}`);
if (orphanZhPages.length > 0) problems.push(`zh pages not in sidebar: ${orphanZhPages.join(', ')}`);
if (summary.counts.categories !== 10) problems.push(`categories = ${summary.counts.categories}, expected 10`);
if (llmsCount !== 74) problems.push(`llms.txt entries = ${llmsCount}, expected 74`);
// v4 §2 的 11 为评审期口径；基线实测 5（全部位于 create-my-data.md，en 镜像同 5 处）。manifest 为准。
if (anchorAliases.length !== 11)
  console.log(`[inventory] note: anchor aliases = ${anchorAliases.length} (v4 计划写 11；基线实测为准)`);

console.log(`[inventory] zh=${summary.counts.publicZhDocs} en=${summary.counts.publicEnDocs} categories=${summary.counts.categories} mediaUnique=${summary.counts.mediaUniqueByHash} orphanMedia=${summary.counts.orphanMedia.length} denyPages=${oldPages.length} denyMedia=${oldMediaUrls.length} anchors=${anchorAliases.length} routes=${routes.length}`);
if (problems.length > 0) {
  console.error('[inventory] PROBLEMS:');
  for (const p of problems) console.error(`  - ${p}`);
  process.exit(1);
}
console.log('[inventory] ALL CHECKS PASS');
